### ISSUE TITLE
Fix a spelling error

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#10]
* In the code itself (or in code comments)
* In the documentation (docs/ directory or the readme file)
* On the website (see the gh-pages branch)

Chat: https://gitter.im/mindfulness-at-the-computer/Lobby

Multiple people can work on this issue

If you can't find a spelling error then please feel free to suggest an improvement of a sentence instead, perhaps changing a word or the sentence structure

If you like the project you can help out by "starring" the project <3

***

Update: If you are using the [Pycharm IDE](https://www.jetbrains.com/pycharm/download/#section=linux) (community edition) you can see a list of files and the spelling errors they have by (from the menu) choosing "Code" -> "Inspect Code..."

![image](https://user-images.githubusercontent.com/10245688/38988836-f10fabd8-43d4-11e8-82d7-c70bf9ac29c0.png)

Also for each file you can hover over the checkmark in the upper right of a file to see if the file contains any spelling errors:

![image](https://user-images.githubusercontent.com/10245688/38988576-eabb1462-43d3-11e8-859f-358c76873143.png)

(This doesn't give the reference to the place in the code where there is a spelling error though, so the above approach may be better)

**Comment by AlphaSoldier** [comment]
Hi! First timer here....
Sorry for troubling you but could you guide me through sending a Pull Request for the listed issues.

**Comment by SunyataZero** [comment]
Hi and thank you for your interest in helping out with Mindfulness at the Computer. I'll be happy to help you with anything you need. If you need help with anything we can use gitter to chat if you like? Either in the "lobby" for MatC
https://gitter.im/mindfulness-at-the-computer/Lobby
or in a "private room" on gitter (if you click on my avatar in the upper right corner (a black and white dog - my dog Siiri :) ) you will get the option to chat privately. I live in Sweden (UTC+2) but often stay up late

Kind Regards,
Tord

**Comment by andy5995** [comment]
@SunyataZero , that's the same guy who submitted PR #11 :)

**Comment by SunyataZero** [comment]
Okay, i just didn't know what he would read first so wrote a welcome message in two places

**Comment by YendyH** [comment]
Hello. I would like to contribute to the .idea file (not sure if I have to comment/claim first...) 
Thank you!

**Comment by SunyataZero** [comment]
Hi and thank you for wanting to help out with this project! You can make a pull request when you are ready (no need to comment). If you need help with anything please don't hesitate to ask, either here or in the [gitter chat](https://gitter.im/mindfulness-at-the-computer/Lobby) or just by emailing me at tord(dot)dellsen(at)gmail(dot)com
Kind Regards, Tord

**Comment by unix-root** [comment]
@SunyataZero Can I take this issue ??

**Comment by SunyataZero** [comment]
@unix-root Yes, please go ahead! Kind Regards, Tord

**Comment by aditya81070** [comment]
Can I also take this issue?

**Comment by SunyataZero** [comment]
@aditya81070 Absolutely! Kind Regards, Tord

**Comment by Jai-Z** [comment]
I'd like to contribute too!

**Comment by SunyataZero** [comment]
@Jai-Z Thank you for wanting to help out with the project, and you are most welcome to contribute! If there's anything you need to ask you can use our gitter chat here: https://gitter.im/mindfulness-at-the-computer/Lobby Kind Regards, Tord

**Comment by cgassman** [comment]
@SunyataZero as this is my first contribution to an open source project ever, just fyi, I fixed two spelling issues errors on the webpages. Will make a pull request now and hope everything goes well.

**Comment by SunyataZero** [comment]
@cgassman Thank you for your help, every looks good and i've now merged the improvements, i'm glad that there is a chance for people to collaborate using git and github. Kind Regards, Tord

**Comment by MaskyS** [comment]
Hey, maybe you should close this issue since the typos have been fixed? :D

**Comment by gsmods** [comment]
i wanted to contribute to this work as its my first contribution

**Comment by SunyataZero** [comment]
@gsmods Hi and welcome! I have sent a message in the gitter chat and will be available there for a couple of hours. Kind Regards, Tord

**Comment by MagdaZawora** [comment]
Hi @SunyataZero! Still looking for help with the issue?

**Comment by SunyataZero** [comment]
@MagdaZawora Yes! Please feel free to work on this issue. If you use an IDE like Pycharm i believe it can help you find spelling errors. Kind Regards, Tord

**Comment by samie820** [comment]
Hey I am really interested in contributing to the project, hope i am not too late?

**Comment by SunyataZero** [comment]
@samie820 Hi, you are very welcome to contribute! (And i'm happy to hear about your interest in the project). I'm not sure how many spelling errors are left but if you can't find any maybe you can improve a sentence in the documentation or in the code comments? Kind Regards, Tord

**Comment by flyer2403** [comment]
Hi @SunyataZero I've corrected one spelling and two grammatical errors (eg. lot time -> lot of time) in the theory-and-background.md and user-perspective.md files. Will make a pull request.

This is my first contribution to Github, so thanks for this opportunity!

**Comment by SunyataZero** [comment]
> This is my first contribution to Github, so thanks for this opportunity!

Thank you for sharing this, i'm glad to hear you are making your first contribution with our project!

**Comment by jgarciabu** [comment]
I've submitted a PR for typo corrections on 1 code file and 1 how to file.

**Comment by GonzaloUlla** [comment]
Me too, I've just made PR #326 to correct some typos on 5 different files: 1 code file and 4 how to files. Thank you very much for giving me this chance to make my first contribution!!
