### ISSUE TITLE
Systray icon behavior is the same for left and right mouse clicks on MacOS

### ISSUE THREAD

**Issue by mbed67** [mindfulness-at-the-computer/mindfulness-at-the-computer#102]
On MacOS (Sierra 10.12.6), given the main window is minimized and I'm not in full-screen mode
when I left-click or right-click (both have the same effect) on the systray icon, 
then the main window is restored and I see the systray menu
I heard right and left clicks should behave differently, but they don't on my machine.

Both clicks give the following log output: DEBUG: entered on_systray_activated. i_reason = 3

**Comment by SunyataZero** [comment]
Closing this since this functionality has been removed for all systems (we are now handling the systray in the default way for Qt)
