### ISSUE TITLE
Asking developers to work on the project with a positive motivation

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#103]
> don't do anything except with the joy of a small child feeding a hungry duck

I sometimes get messages from people saying "i'm sorry i can't contribute more" etc and i'm concerned that people may do things on the project partly with a "should"/"ought" motivation/intention

I'd like to include text - perhaps in README.md - that makes it clear that we want people to do things "with the joy of a small child feeding a hungry duck"

**Comment by ap1459** [comment]
Hi @SunyataZero, I think this is a fantastic idea and would love to have a go at contributing towards this. Perhaps going on what you have already mentioned and include it in the README.md?

**Comment by SunyataZero** [comment]
@ap1459 Hi and welcome! I'm glad you like this idea, our motivation when working is so important. Yes please include something in the readme file, if you [create a PR](https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/blob/master/CONTRIBUTING.md#pull-requests) with some changes we can discuss further if you like? Kind Regards, Tord
