### ISSUE TITLE
Helpful information on how to practice?

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#109]
For example:
* asking the user to sit upright
* asking the user to breathe with her stomach
* explaining what mindfulness is - update: this is now covered on the home page (thank you @ap1459 for your contribution!)
* explaining the benefits of mindful breathing

**Comment by SunyataZero** [comment]
We have decided to keep this type of information out of the application itself. The reason is that we want things to be simple. Now we need to decide if we want this info on the website, or even just links to more information about mindfulness and how it can best be practiced

**Comment by SunyataZero** [comment]
I like the mini-tutorials given by breathaware.com in their automated emails

**Comment by milkmiruku** [comment]
I'm enjoying the app, thanks! I'm wondering about the possibility of something like breathing messages 'playlists', so the program could load/create a set of messages in order, with however long a break. If each playlist was a file, some could be core and some contrib. I'm interested in enumerating through fairly abridged various aspects of the [Satipatthana](http://dharmafarer.org/wordpress/wp-content/uploads/2009/12/13.4-Satipatthana-Mula-m10-sujato.pdf), though it could also be used for more guided meditations or other such choice reminders.

**Comment by SunyataZero** [comment]
@milkmiruku Hi and thank you for your feedback, i'm also interested in Buddhism, and this is the direction that we come from when we have designed the application. Are you willing to discuss this and other design-related ideas in our gitter chat? https://gitter.im/mindfulness-at-the-computer/design
