### ISSUE TITLE
Internationalization of GUI Elements

### ISSUE THREAD

**Issue by yigitsever** [mindfulness-at-the-computer/mindfulness-at-the-computer#121]
Are there plans for translating the application to languages other than English?
A quick Google revealed it's pretty easy ([case 1](https://kuanyui.github.io/2014/09/03/pyqt-i18n/) [case 2](https://www.pythonstudio.us/pyqt-programming/internationalization.html)) with PyQt  (sorry if this is common knowledge for anyone)

So, linked with #113 (maybe #109), user strings should handle internationalization

**Comment by yigitsever** [comment]
After #130, suggesting this to stay open like #71 because it can be easy to miss wrapping strings with tr() calls

**Comment by SunyataZero** [comment]
Just a note for translators:

> Keyboard accelerators may need to be changed but without introducing conflicts. For example, "&Quit" in English becomes "Avslutt" in Norwegian which does not contain a "Q". We cannot use a letter that is already in use - unless we change several accelerators.
