### ISSUE TITLE
Breathing Phrase List & Rest Action List Bugs

### ISSUE THREAD

**Issue by yigitsever** [mindfulness-at-the-computer/mindfulness-at-the-computer#151]
### Breathing Phrase List
- Clicking Edit / Move To Top / Move Up / Move Down  immediately after deleting a phrase crashes the applicaton (When no phrase is selected, it defaults to first phrase)
`TypeError: type object argument after * must be an iterable, not NoneType`

### Rest  Action List
- Clicking Edit / Move To Top / Move Up / Move Down without picking a rest action (without a highlighted rest action) crashes the application
`TypeError: type object argument after * must be an iterable, not NoneType`

Two lists do not behave similarly on same situations

**Comment by SunyataZero** [comment]
Thank you for reporting this, i've fixed a few of these issues but am continuing to work on the others. Maybe you're right that we need to have a more OO approach to this

**Comment by yigitsever** [comment]
Currently move up/down and to top/bottom does not respond for either of the lists regardless of a list selection or not

Edit is not responsive for breathing list

Editing rest actions crashes the application

**Comment by SunyataZero** [comment]
@yigitsever 

> Currently move up/down and to top/bottom does not respond for either of the lists regardless of a list selection or not

This has now been fixed, but unfortuantely the database needs to be deleted for the changes to take effect (see gitter discussion about implementing fixes for existing databases)

> Edit is not responsive for breathing list
> 
> Editing rest actions crashes the application

I cannot see these problems, can you delete your .db file and start and see if you can find this again? And can you write a new issue/issues when you do?

Thank you for your patience!

Kind Regards, Tord

**Comment by SunyataZero** [comment]
Closing this issue as the problems mentioned in the issue are no longer there
