### ISSUE TITLE
[xfce]Second window on 1st run ("How to use this wizard") opens with too small of geometry for contents

### ISSUE THREAD

**Issue by dgets** [mindfulness-at-the-computer/mindfulness-at-the-computer#185]
Upon the first run on my Debian 9 system, running xfce, the 2nd window which opened, titled _How to use this wizard_ opened with a geometry insufficient for the 4th numbered point text line at the bottom.  Not sure if this happens on all platforms, but it at least has the capability for this inconvenience.

The window could be resized, so it was not hard to expand and view the 4th point, but this is a point that should probably be addressed for the general end user.

**Comment by SunyataZero** [comment]
The intro dialog has now been changed with new pages, thank you @mbed67 !

@dgets Can you look to see if the contents of the pages in the new design are fully shown on XFCE?

**Comment by SunyataZero** [comment]
@dgets Hi, when you have time could you look at this? You can either run from source or use our new alpha 5 release build: https://diasp.eu/posts/87b8bba035c40136c5074061862b8e7b
