### ISSUE TITLE
Rest list box same height as the breathing list box?

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#206]

**Comment by TheConObs** [comment]
I know I brought this one up but could be tricky given the fluidity of the screen contents as you drag the corner around and things resize "responsively" not to mention the differences between platforms.

Hmm...

**Comment by SunyataZero** [comment]
@TheConObs Okay, but it can be good to have this here so we are aware, not sure how other applications deal with this sort of thing, Qt has a lot of options when it comes to resizing, you can add "stretches" which fills up unused space a specified percentage for example

**Comment by SunyataZero** [comment]
I'll move this into the larger issue [Improving the layout for the settings window?](https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/issues/193)
