### ISSUE TITLE
Presenting the benefits of mindfulness

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#217]
Perhaps on the website

WIP can be seen here: https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/wiki/Mindfulness

**Comment by ap1459** [comment]
Hi again @SunyataZero , I noticed this was topic was mentioned but not answered on the FAQ page on the Wiki. I would love to have a go at contributing to this! Though I'm not sure how I could add it to the website as the relevant HTML and CSS files are not available in the repository. Have I missed something or are they not a part of this repository? 

At any rate, I would be happy to write something for the Wiki page and that could always be moved at a later date to the website? Or perhaps be available through both mediums? What are your thoughts?

**Comment by SunyataZero** [comment]
@ap1459 Good questions! I'll move this discussion [here](https://gitter.im/mindfulness-at-the-computer/Lobby), (hope that's okay)

**Comment by SunyataZero** [comment]
Has now been added to the website: https://mindfulness-at-the-computer.github.io/mindfulness/
