### ISSUE TITLE
Adding a phrase about the posture

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#218]
This is related to this issue: #215 Adding a note about the posture as an alternative help text can be one way to achieve the same goal

**Comment by yigitsever** [comment]
+1 from me, although user can add a custom long breathing phrase or rest action (i.e. Sit upright and relax)

**Comment by SunyataZero** [comment]
Closing this issue as we now have added a preparatory notification which includes a note on the posture

PR: https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/pull/242
