### ISSUE TITLE
Using relative paths for the audio and other files

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#221]
The advantage of this would be that we can move the application and the application will still work. It would be "portable", (it would be possible to have the application running from an usb drive for example)

One of our users have requested this feature (to make the application portable)

**Comment by SunyataZero** [comment]
When choosing variable names for the database it may be good to call it "relpath" instead of just "path", for example instead of `self.breathing_reminder_audio_path_str` we can write ``self.breathing_reminder_audio_relpath_str

**Comment by JedMeister** [comment]
I'm not a python programmer, so I have no idea how this "should" be done. But I imagine that if you have a `base_dir` or `install_dir` variable defined, then you could easily use relative paths by simply adding the relative path the to `base_dir`. I.e. `path_to_file = base_dir + relpath`.

Having said that, I'm sure that there's probably a "best practice" way of achieving that.

**Comment by SunyataZero** [comment]
WIP on open PR: https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/pull/254

**Comment by SunyataZero** [comment]
Now implemented in this PR: https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/pull/254

**Comment by SunyataZero** [comment]
(This has now been verified as working in a build)
