### ISSUE TITLE
Cleanup of background noise for audio files

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#223]

**Comment by yigitsever** [comment]
Can you elaborate? files under /user_files/audio do not have background noise as far as I can tell

**Comment by SunyataZero** [comment]
It's barely noticeable but i could hear some birds chirping etc when increasing the volume on my brother's computer. This is perhaps such a low-prio issue that we can close it?

**Comment by yigitsever** [comment]
I don't see it as an issue at all, I thought it was intentional

**Comment by SunyataZero** [comment]
Okay, i'm closing this, one less issue to worry about!
