### ISSUE TITLE
Only allow a single instance to run

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#224]
One approach is to use a lock file, the problem with this is if the application exits with a segfault for example

Two ways to hook into the exiting of the application:
* http://doc.qt.io/qt-5/qcoreapplication.html#aboutToQuit
* https://stackoverflow.com/questions/19127777/a-python-segmentation-fault

We can warn the user using a popup if the application is already running, here we could also say that if the application quit from a segfault the user needs to remove the lock file manually

**Comment by JedMeister** [comment]
What about a warning that the application "appears to be already running", with an option for the user to "force start" (and for the app to remove the lock file for the user)?

On Posix systems (e.g. Linux, BSD, MacOS, ...) there are a range of ways to check for a running process which would in some ways be superior to a lock file (for [example](https://stackoverflow.com/a/31997847/3363571)). But that would require an alternate method for Windows and IMO cross platform software is easier to maintain when as much of the code as possible is consistent across OS.

**Comment by SunyataZero** [comment]
> What about a warning that the application "appears to be already running", with an option for the user to "force start" (and for the app to remove the lock file for the user)?

I like this approach, what do you think @deepthinidwannaya ?
