### ISSUE TITLE
Implementing Doctests and Unittests

### ISSUE THREAD

**Issue by yigitsever** [mindfulness-at-the-computer/mindfulness-at-the-computer#228]
> the unittests are sort of used to do GUI-system testing, so i guess the doctests can be used to do unit testing 

This issue regards implementing Doctests where the functionality should be throughly documented and unittests where we can silently test functionality (e.g. on_move_to_top_clicked)

**Comment by georgedorn** [comment]
In my experience, unit tests are generally preferable to doctests; it's too easy to accidentally stop running doctests when upgrading python or switching test runners.

However, there are ways to explicitly find and execute doctests, depending on the test runner.
