### ISSUE TITLE
Make sure the application is installed in such a way that it runs on startup

### ISSUE THREAD

**Issue by mbed67** [mindfulness-at-the-computer/mindfulness-at-the-computer#230]
Right now, when you reboot your computer, you have to manually start the application again. Users may forget this. A setup script can be made that can be run optionally.

* [x] MacOS - mbed67
* [ ] Windows
* [ ] GNU/Linux

**Comment by JedMeister** [comment]
Should be fairly easy on Linux. so it should be possible to provide 3 variants, one each for Mac, Windows and Linux. I know nothing about Mac and am very rusty with Windows, but Linux should be easy. :smile: 

This should work for most (if not all Linuxes):
```
PATH_TO_EXECUTABLE=/path/to/mindfulness-at-the-computer/app
cat > ~/.config/autostart/mindfullness.desktop <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=mindfulness-at-the-computer
Comment=mindfulness-at-the-computer startup script
Exec=$PATH_TO_EXECUTABLE
StartupNotify=false
Terminal=false
EOF
```

**Comment by mbed67** [comment]
MacOS has two ways of doing this. You can either use a launchd .plist file, which can be installed in ~/Library/LaunchAgents. But this doesn't keep the regular user 'in control'.
The other ways is that as a user, you can choose which applications to run on login by going to System Preferences  - Accounts - Login Items and adding mindfulness-at-the-computer.
This way the user can easily remove the app from this list if desired. 
How about if I add an instruction file to the dmg? @SunyataZero

**Comment by JedMeister** [comment]
@SunyataZero pointed me to this existing desktop file: https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/blob/master/varia/mindfulness-at-the-computer.desktop

That should do the trick! If we copy that to `~/.config/autostart/` then it should all "just work" :tm: ! 

@mbed67 - when you say adding a `.plist` file to `~/Library/LaunchAgents` "doesn't keep the regular user 'in control'" what do you mean?! Isn't that directory within your home directory? 

In Linux `~` is an alias for the user's home directory (e.g. `/home/user`), so all files within are owned and accessible by the user. I had always guessed that Mac does the same thing?! 

In my mind, if Mindfullness@PC creates a `.plist` file (e.g. `mindfullness.plist`) in `~/Library/LaunchAgents` and that would make it autostart, then that's fine. That is assuming that the removal of that same `.plist` file would in turn disable autostart on login.

Or am I missing something fundamental here? (I guess I must be??)

**Comment by mbed67** [comment]
@JedMeister You are right that the user has control over the `~/Library/LaunchAgents` directory. However, I assume that most mac users will know about `Preferences - Accounts - Login Items` and not about the `~/Library/LaunchAgents`. So if they would want to undo it, that would not be the place for them to search. I thought that adding something to Login Items manually would add a .plist file somewhere, but that isn't true. It adds an entry to a file that you shouldn't edit.

**Comment by JedMeister** [comment]
@mbed67 - Perhaps I'm missing something, but I'm envisioning, that it would be a checkbox within the app's config page. Something like:

:ballot_box_with_check:  auto start on login 

And that the app itself writes (or removes, as appropriate) the required file behind the scenes. So how "user friendly" the process is at this stage is not so important IMO. It's more a matter of making sure it works. Perhaps the `.plist` file could also go in the [varia](https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/tree/master/varia) directory?

So long as it's documented clearly, copying a file from one location to another, isn't that unfriendly anyway, at least IMO (although I spend lots of time at the commandline, so I'm biased...).

**Comment by mbed67** [comment]
@JedMeister `checkbox within the app's config page`: I like the idea of that! 
About the user-friendliness, I do think it is important, also at this stage. I don't like the idea of the user having to google his or her way out of a situation. But a checkbox at the config page seems like a good idea to me :-)
The varia directory is not a directory that is seen by launchd, the service that makes sure that agents are run on startup. So we can't put it there...
