### ISSUE TITLE
Don't show (skip) the breathing notification if the breathing dialog is shown

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#231]

**Comment by chef-mukul** [comment]
What do you mean by breathing notifications?

**Comment by SunyataZero** [comment]
@chef-mukul I realize now that this is not described anywhere, but the breathing notification is this popup shown in the lower right corner:

![image](https://user-images.githubusercontent.com/10245688/36870578-e122317e-1d9f-11e8-9b1f-75b51220fc8f.png)

(And the breathing dialog is the interactive dialog in the middle center of the screen)

**Comment by SunyataZero** [comment]
PR: #245
