### ISSUE TITLE
[Qt 5.10] Error - This Windows version does not support the required Bluetooth API

### ISSUE THREAD

**Issue by chef-mukul** [mindfulness-at-the-computer/mindfulness-at-the-computer#234]
![error_blutooth_pyqt5 10](https://user-images.githubusercontent.com/9193291/36872272-bb83a418-1dca-11e8-814c-f2e99e013272.JPG)

System - Windows 8.1
PYQT - 5.10

This error was resolved after i revert back to PyQT 5.9

Additional details :- https://stackoverflow.com/questions/48514027/spyder3-python-ide-does-not-start-this-windows-version-does-not-support-the-re

**Comment by altendky** [comment]
`import PyQt5.Qt` imports everything including bluetooth.  While that import looks nice for the sake of only having one it does cost in scenarios such as this.  So, just use the regular imports like `import PyQt5.QtWidgets` instead.

**Comment by altendky** [comment]
https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/blob/1c40b37352b37bdb59f9a6bd9f0dfbe1ee273df7/mindfulness-at-the-computer.py#L6

There's one case at least.

**Comment by altendky** [comment]
@InUrSys, 'just keep using an old version forever' isn't great advice.  Especially when the OP already identified that as a way to avoid the issue.

**Comment by InUrSys** [comment]
I agree with you @altendky , but this looks like a bug or something inside the PyQt5.10 and in that case I would rather use an old stable version than a new with bugs. idk maybe im thinking of it the wrong way.

**Comment by altendky** [comment]
From the error message (and https://bugreports.qt.io/browse/QTBUG-40698) it appears to be a Qt platform support...  thing.  They support bluetooth on Windows only for >= 10 at this point.  I'll admit this is a tight requirement for Qt to enforce, but so it goes.

I had just found out about `PyQt5.Qt` recently and was interested in it, but given that it loads every module available thus using memory (no clue how much, not a huge deal to me, but still) and exposes you issues that any module has being imported, it seems maybe not worthwhile.

Of course, it's a personal choice.  I'd obviously choose adjusting imports to improve robustness (and bypass the present issue) over sticking with an old version indefinitely.  Luckily, I don't need Bluetooth or I'd be more frustrated.  Maybe you could talk Phil into finding a way to handle the Qt issue better so as to be able to continue using `PyQt5.Qt` imports on more versions of Windows.

For completeness: https://www.riverbankcomputing.com/pipermail/pyqt/2018-July/040617.html
