### ISSUE TITLE
Request for contribution

### ISSUE THREAD

**Issue by Theonimfi** [mindfulness-at-the-computer/mindfulness-at-the-computer#236]
I just download the mindfulness at the computer.I found your idea really interesting and usefull and I'd like to contribute to this. Is there anything that needs improvement?

**Comment by SunyataZero** [comment]
@Theonimfi Hi and welcome! I saw that you had a discussion with Marieke and she gave some great links. Also there is this chat room if you want to check it out: https://gitter.im/mindfulness-at-the-computer/Lobby Kind Regards, Tord
