### ISSUE TITLE
[Windows] Norton antivirus removes the .exe file without giving the option to keep the file

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#238]

**Comment by JedMeister** [comment]
Certainly an issue worthy of note, however, I question whether this is a mindful@PC bug?! 

IMO it's a Norton bug, with a simple solution: uninstall Norton and get a decent reputable anti-virus! :rofl: - Sorry, joking...!

It may be worth sending then an email with a copy of the `.exe` and ask for their advice on avoiding their AV heuristics?

Also, whilst it may not be possible to explicitly keep the file once it's been flagged, it should be possible to whitelist the file and/or directory?!

**Comment by SunyataZero** [comment]
@JedMeister The user named Mat wrote the comment here: https://discourse.suttacentral.net/t/mindfulness-at-the-computer-alpha-4-release/8354/4

I don't like it that he doesn't even have an option to continue or whitelist
