### ISSUE TITLE
Adding a "copy" button to the system information dialog

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#246]
-to make it easier for users to provide system details with bug reports etc

**Comment by emwani1** [comment]
Is any working on this?

**Comment by SunyataZero** [comment]
@emwani1 Hi, sorry i forgot to assign myself to this issue, i've just completed a PR. I can try to find another issue for you though if you like?

**Comment by emwani1** [comment]
@SunyataZero  Yes that will be nice

**Comment by SunyataZero** [comment]
@emwani1 Can you join us here in the application chat? https://gitter.im/mindfulness-at-the-computer/Lobby
And welcome!
