### ISSUE TITLE
Feature suggestion: Sync multiple computers

### ISSUE THREAD

**Issue by georgedorn** [mindfulness-at-the-computer/mindfulness-at-the-computer#250]
I use two computers at my desk (with a KVM) and would like both to prompt with reminders at the same time, in case I'm not looking at the one running the app at the time, and to reduce my subconscious urge to take a 'break' from one by switching to the other.

This probably requires some networking.  Some ideas:
- run a lightweight web daemon; designate one instance as the server; use the server's configuration, and clients just repeat what the server does.  Requires configuring clients to know who the server is.
- perhaps bonjour could assist with autodiscovery and message transmission?
- run a headless web daemon on a VPS; particularly useful for tracking stats in one place for computers in multiple locations (work, home)

I might take a crack at implementing this myself, when I'm in the right headspace.

**Comment by SunyataZero** [comment]
@georgedorn Thank you for reporting this, and i'm glad to hear that you are using the software! Yes please feel free to try to solve this if you want (i'm not good at web programming myself unfortunately). Also you can join us here if you want to brainstorm different approaches/ideas: https://gitter.im/mindfulness-at-the-computer/Lobby

**Comment by SunyataZero** [comment]
@georgedorn I looked at [workrave](http://www.workrave.org/) and they seem to use the local network for this:

![image](https://user-images.githubusercontent.com/10245688/38256029-a26412c2-375d-11e8-807e-6883b33e5d1a.png)

![image](https://user-images.githubusercontent.com/10245688/38256091-ca523b42-375d-11e8-9791-0cefb7fd326b.png)
