### ISSUE TITLE
Display remaining time in the systray icon

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#255]
Maybe using a vertical mini-progress-bar

When we have implemented this we can also remove the boxes shown in the sytray menu

**Comment by SunyataZero** [comment]
What about the time remaining until the next breathing pause?

**Comment by SunyataZero** [comment]
We have decided that the tooltip is enough. However this tooltips is not visible on LXDE (unknown why)

**Comment by milkmiruku** [comment]
Possibly as AppIndicator based GUIs don't do tooltips? https://bugs.launchpad.net/indicator-application/+bug/527458
