### ISSUE TITLE
Deciding on what breathing phrase to show in the breathing dialog

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#256]
We could allow the user to choose between different options:
* random
* (next)
* same (this is what we have right now)

and we could even make the application smart and randomize if the same phrase will be used or if it will change always between two breathing notifications:
* always change
* change after x number of times
* change with x percentage chance

#### User perspective

I (Sunyata) have been using the application for a while now and i've actually stopped changing the phrase! So i would benefit and maybe the same is true for other users as well. It may be that users need to use the application for a couple of weeks before being able to give this sort of feedback since at the beginning they may be interested in playing with the settings in the breathing dialog

**Comment by mbed67** [comment]
I think I would benefit as well from such a feature

**Comment by SunyataZero** [comment]
Random and same has now been added as options in the application settings. Reference: https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/pull/254
