### ISSUE TITLE
Can't run the program on Windows 10

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#260]
Hi,
I downloaded WINDOWS ALPHA 4 from here:
https://mindfulness-at-the-computer.github.io/downloads/
Then I unzipped the archive and when I double click mindfulness-at-the-computer.exe
I get the following error:
![1](https://user-images.githubusercontent.com/8938883/38339175-92438dbe-3875-11e8-919e-be326aea4c58.png)

***

Reported by @theprofi originally

**Comment by SunyataZero** [comment]
@theprofi Hi and thank you again for reporting this problem, i've been working on finding a solution for a while now, can you try this special build that i made? https://drive.google.com/file/d/1c1_4oh_6RQ-YUUMOQhwVyMcHMBQRU2Wa/view?usp=sharing

**Comment by theprofi** [comment]
It works!

**Comment by SunyataZero** [comment]
Oh, i'm very glad to hear this! Now we can release alpha.5!!!
