### ISSUE TITLE
Encouraging the user to leave the computer, and maybe only for a short while

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#282]

**Comment by Krafty-Coder** [comment]
Can you please add more details to this issue. A description would do... Seems interesting and would like to contribute to as my first in this project

**Comment by SunyataZero** [comment]
@Krafty-Coder Hi and welcome! We have now moved to gitlab, and we have a few issues with the "good first issue" label: https://gitlab.com/mindfulness-at-the-computer/mindfulness-at-the-computer/issues?label_name%5B%5D=good+first+issue
