### ISSUE TITLE
New rest dialog design

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#297]
Ideas:
* Nature background
* Hiding the rest actions
* Allowing the user to simply leave the computer (without even seeing the rest dialog itself) when seeing the rest notification in the upper right corner - this would reduce the number of clicks and make things easier for the user

**Comment by milkmiruku** [comment]
My suggestion for the Rest screen would be to give the Rest Action list radio buttons so the user can choose one. These action choices would be logged, reported on like with breath session data, and some kind of message alongside the Action in the Rest screen list could show, allowing awareness of unattended actions.

Also, there could be buttons selecting a task; "Random Action" ("I'm feeling lucky"), plus a "Recommended Action" button/algorithm ("I-have-avoided-it-myself-so-let-the-computer-tell-me-to-do-it").

**Comment by SunyataZero** [comment]
> Also, there could be buttons selecting a task; "Random Action" ("I'm feeling lucky"), plus a "Recommended Action" button/algorithm ("I-have-avoided-it-myself-so-let-the-computer-tell-me-to-do-it").

@milkmiruku I like this idea, because i myself sometimes avoid some things and forget to do them

Previously we have been having an image for each rest action so that the user can select one and see the image

What i'm worried about is that the user thinks that she only want to do one of the rest actions, and also we have been trying to keep the application to mainly the computer and not dealing much with the outside

I still would like to find some way that we can allow the user freedom and at the same time gently encourage her to try new things when she is taking a rest

**Comment by SunyataZero** [comment]
@milkmiruku For me the most important improvement i see is if we could somehow help the user remember to do mindful walking. I forget to do this myself so would like to have better support from the application in this regard. Not sure how to do it though, and we already are encouraging the user using the text shown on the rest screen

Somehow adding mindful walking would be a huge benefit i think. One idea i had a few months ago is to have a checkbox asking the user if she was able to walk mindfully

**Comment by milkmiruku** [comment]
I think there's scope for an option for extra walking reminders, given how bad a sedentary lifestyle is for one, though I wouldn't use it (I personally want to make the call on some actions), but the biggest stopper for that atm is cleaning up the settings window, it's quite crowded ;)

An image based system sounds tricky - with the default actions, it would arguably be a fair chore to find a whole matching set of images with an appropriate aesthetic to match, but then if users want to create their own actions it might be a bit much for them to find appropriate images of the right fit/size/quality, etc.

If more than one action can be done/logged a rest break, use check boxes not radio buttons. Have a message like "Select the actions you are doing in this break", rename "Close" as "Return from Break" (and "Close and Breathe" to "Return and Breathe") and add a "Cancel break" button to not log anything.

Tbh, my original thought was either just for an automatic random prompt for what to do, but logging seems to be something the app does, so 2+2=my suggestion above.

**Comment by SunyataZero** [comment]
Thank you for taking the time to consider how to improve the application! Please see comments below

> cleaning up the settings window

Marieke (mbed67) is working on this!

> An image based system sounds tricky - with the default actions, it would arguably be a fair chore to find a whole matching set of images with an appropriate aesthetic to match, but then if users want to create their own actions it might be a bit much for them to find appropriate images of the right fit/size/quality, etc.

What we did in an earlier version was to find a set of images and then use some of them for the included actions, and have other nice images as well, but yes it can be hard to find the perfect image and then also do the scaling

> Tbh, my original thought was either just for an automatic random prompt for what to do, but logging seems to be something the app does, so 2+2=my suggestion above.

We are considering whether to keep the logging, or to at least hide it more than now, Marieke is working on this now that she is dealing with the settings interface. 

> If more than one action can be done/logged a rest break, use check boxes not radio buttons. Have a message like "Select the actions you are doing in this break", rename "Close" as "Return from Break" (and "Close and Breathe" to "Return and Breathe") and add a "Cancel break" button to not log anything.

My thinking is to make things easier, i've even been thinking of allowing the user to not use the rest screen, but instead just leave this dialog up when taking a break:

![image](https://user-images.githubusercontent.com/10245688/40542181-4b6b5c6a-601f-11e8-81b4-2d1c8509bc37.png)

but perhaps change the text of the "skip" button to "start" or something like this. The aim is to reduce the required interaction with the application as much as possible. What do you think about this approach?

**Comment by milkmiruku** [comment]
Very fair on keeping it easy, though part of the reason I came to Workrave originally was that it hides the screen as well as disabling all input access (only issue was not being able to stop a video (or rather, the next video, thanks to autoplay) on YouTube, though that certainly doesn't happen every time, and I can always hit the volume (on my stereo)). But yeah, KISS is good.
