### ISSUE TITLE
Request for breath dialog instruction alteration

### ISSUE THREAD

**Issue by milkmiruku** [mindfulness-at-the-computer/mindfulness-at-the-computer#306]
1) For clarity, "Hover over the central area..." could be "Hover over the green box..."

2) The pointer being anywhere else but the green box counts as breath out, so maybe worth changing the "...over the background breathing out" text to "and away from the greenbox breathing out"

3) Overall, I would suggest; "Hover over the green box whilst breathing in and away from the green box whilst breathing out."

**Comment by SunyataZero** [comment]
@milkmiruku That's better i agree! It was implemented here: https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/pull/308 by @jgarciabu
