### ISSUE TITLE
'Viewport' in breath dialog box doesn't resize on dialog resize

### ISSUE THREAD

**Issue by milkmiruku** [mindfulness-at-the-computer/mindfulness-at-the-computer#307]
With deep breaths, the text can become larger than the breath message viewport and thus obscured. Resizing the dialog doesn't resize the message viewport, it would be handy if it did.

**Comment by SunyataZero** [comment]
@milkmiruku Okay, interesting, let's keep this issue until later. It's also possible that we may want to set a limit for how large the box and text can become (we have set a minimum limit already)
