### ISSUE TITLE
Settings window shows on launch

### ISSUE THREAD

**Issue by milkmiruku** [mindfulness-at-the-computer/mindfulness-at-the-computer#311]
It would be nice to have an option to disable showing the settings window on program start.

**Comment by SunyataZero** [comment]
@milkmiruku On my system (LXDE / Lubuntu) the settings window is minimized when starting the application, is it different on your system?

**Comment by milkmiruku** [comment]
Yes, I'm using i3wm. On starting the script, the settings window appears.

**Comment by SunyataZero** [comment]
Okay, i see the problem now in the code, i've created a PR for this: https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/pull/315 Will merge after i get the okay from Marieke

Thank you for reporting this! It was actually a problem on my system as well (though it showed itself differently)

**Comment by SunyataZero** [comment]
All right, this issue should be fixed now, will be included in the next release!
