### ISSUE TITLE
Error When Running from Source

### ISSUE THREAD

**Issue by jgarciabu** [mindfulness-at-the-computer/mindfulness-at-the-computer#313]
Haven't had a chance to research. Wanted to make all aware I got this error while I was running from source. I had stopped paying attention to the configuration screen to answer some texts for a few minutes. When I looked back up Python crashed and this message was in the debug console. I was at the finish window of the initial set up process. 

Traceback (most recent call last):
  File "C:\Users\XXXX\Desktop\XXXX\mindfulness-at-the-computer-master\mc\gui\main_win.py", line 573, in breathing_timer_timeout
    self.commence_breathing_notification()
  File "C:\Users\XXXX\Desktop\XXXX\mindfulness-at-the-computer-master\mc\gui\main_win.py", line 577, in commence_breathing_notification
    logging.debug("self.breathing_dialog.isVisible = " + str(self.breathing_dialog.isVisible()))
AttributeError: 'NoneType' object has no attribute 'isVisible'

**Comment by SunyataZero** [comment]
@jgarciabu Thank you for reporting this! Are you sure you are using the latest version? I remember that we had a similar (if not the same) problem in an earlier version

**Comment by jgarciabu** [comment]
@SunyataZero Sorry for the late reply. The version I was using was as recent as the day I reported this error. I downloaded the zip file from Github that day and ran from source through my command prompt. When I have some time, I'll delete what I have on my machine and try again with the latest in Github.

**Comment by jgarciabu** [comment]
@SunyataZero Just ran it again today with the latest version as of today downloaded from Github and it happened again. Same error, oddly enough the line numbers have incremented up by 1. 

Traceback (most recent call last):
  File "C:\Users\XXXXX\Downloads\mindfulness-at-the-computer-master\mc\gui\main_win.py", line 574, in breathing_timer_timeout
    self.commence_breathing_notification()
  File "C:\Users\XXXXXX\Downloads\mindfulness-at-the-computer-master\mc\gui\main_win.py", line 578, in commence_breathing_notification
    logging.debug("self.breathing_dialog.isVisible = " + str(self.breathing_dialog.isVisible()))
AttributeError: 'NoneType' object has no attribute 'isVisible'

**Comment by SunyataZero** [comment]
@jgarciabu Okay, thank you for reporting this and for the details, i will assign this issue to myself, hope to get a chance to look at this soon
