### ISSUE TITLE
New feature? Visual feature

### ISSUE THREAD

**Issue by gibsonhan** [mindfulness-at-the-computer/mindfulness-at-the-computer#324]
Hello, I found this repository on an open source site. I would love to contribute. I was wondering how hard would it be to implement this a [visual breather](https://gfycat.com/gifs/detail/MediocreCriminalAsiansmallclawedotter). I was thinking of using react

**Comment by SunyataZero** [comment]
@gibsonhan Oh, that looks nice! Thanks for the tip! I'll add you to our chat on gitter and we can talk more there if you like?

**Comment by SunyataZero** [comment]
@gibsonhan I get an error message when trying to add you, but can you join yourself here? https://gitter.im/mindfulness-at-the-computer/Lobby
