### ISSUE TITLE
Code Review: Back-End

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#53]
Code review of the Python and sqlite3 code, in other words of files in the base of the mc/ directory/package: https://github.com/SunyataZero/mindfulness-at-the-computer/tree/master/mc

Suggestions for how to refactor is welcome!

Please note:
* Multiple people can work on this issue
* You can choose a small part of the code for a code review

**Comment by GonzaloUlla** [comment]
Hi!! I've working on this issue for quite a while, reviewing back-end code myself and using static analysis tools, and here are the results of my code review:

1. I suggest to refactor module mc.model.py as follows:
- Trying to reduce the amount of arguments, attributes and local variables in PhrasesM and SettingsM classes.
- Redefine the if statement under function is_empty(), simplifying it by returning bool and not making two return points.

2. Remove unused or repeated imports and unused variables under mc.gui modules as shown in the attached .txt file.

Thank you very much for letting me have this chance to contribute!
My suggestions are all well-intended and I really hope they could be useful!!
Best regards

[issue_#53_code_review.txt](https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/files/2120474/issue_.53_code_review.txt)

**Comment by SunyataZero** [comment]
@GonzaloUlla Oh, thank you for this, looks very good! Can i ask: Are you willing to implement some of these changes for us?

**Comment by GonzaloUlla** [comment]
@SunyataZero you are welcome! I'm happy to help.
Sure, of course I'm willing to implement those changes, just tell me what you think about them and which are the ones you consider I should put my hands on (maybe I can start removing imports, unused variables and simplifying that if statement, I don't know what you think about the refactor on PhrasesM and SettingsM classes)

**Comment by SunyataZero** [comment]
> maybe I can start removing imports, unused variables and simplifying that if statement, I don't know what you think about the refactor on PhrasesM and SettingsM classes

@GonzaloUlla Yes, that's the best i think also! I'm not sure how to refactor these classes by reducing the number of function arguments
