### ISSUE TITLE
[Linux] Building Debian/Ubuntu Package

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#6]
We have created binaries using [pyinstaller](http://www.pyinstaller.org/) but to make it easier for Ubuntu and Debian users we would like to have a debian package

Todo list:
* [ ] Adding a changelog

Useful links:
* http://packaging.ubuntu.com/html/packaging-new-software.html
* https://wiki.debian.org/Packaging/Intro?action=show&redirect=IntroDebianPackaging

Chat about this issue: https://gitter.im/mindfulness-at-the-computer/packaging

**Comment by SunyataZero** [comment]
This link may be helpful: http://packaging.ubuntu.com/html/packaging-new-software.html I've followed it successfully for the example they gave ("hello") but i'm not sure how to use this for our application

**Comment by andy5995** [comment]
Because Ubuntu is based on Debian, I wonder if it would first be better to build a Debian package, and then adapt the Ubuntu package from that.

Also, are you wanting a package that meets Debian specifications, or just a package in Debian format that can be installed or removed with the Debian package manager.

To make a package that complies with the Debian policies, a few files will need to be added.

https://wiki.debian.org/Packaging/Intro?action=show&redirect=IntroDebianPackaging

Here is one example, mentioned in the link above

> **debian/changelog**
> 
> First file is debian/changelog. This is the log of changes to the Debian package.
> 
> It does not need to list everything that has changed in upstream code, though it can be helpful to users to summarize those changes, too. Since we are now making the first version, there is nothing to log. However, we still need to make a changelog entry, because the packaging tools read certain information from the changelog. Most importantly, they read the version of the package.
> 
> debian/changelog has a very particular format. The easiest way to create it is to use the dch tool.

**Comment by JedMeister** [comment]
FWIW if you can successfully build a Debian package which works, then it can (at least in theory) be rebuilt against any Debian based release and should also work there. As you're probably aware, a Debian package is built within a Debian chroot. You just use a different release chroot to build a different release package.

As @andy5995 notes, if you don't care about it getting into the official Debian repos, then you don't need to follow the Debian packaging policy (although it may still be a good idea). 

If you go that way (i.e. don't do it "properly") and bundle it with it's dependencies (except python itself probably), you may be able to provide a single deb file that will install in most (if not all) Debian based distros/releases everywhere!? You'll never get it into Debian (or Ubuntu) repos like that though...

So it's worth considering whether your primary aim is to just want to make it easier to install in the short term? Or whether you'd like to get it into the official Debian repos (so it will be super easy to install at some point in the future).

If you'd like to get it into the official Debian repos (and Ubuntu too) at some point, then doing it properly right from the start is the best plan IMO. You may still be able to build a generic enough deb that it will install everywhere in the meantime, although YMMV.

**Comment by SunyataZero** [comment]
Hi @JedMeister and thank you for these comments, i actually know almost nothing about packaging sadly but i'm happy to learn. I've created a gitter chat room here and invited both of you if you'd be willing to answer a question or two from me: https://gitter.im/mindfulness-at-the-computer/packaging This seems to be an important conversation for the future of the application (bundling or not)

**Comment by JedMeister** [comment]
I know enough to be dangerous! :smile: It's actually something I have a bit to do with through work. Within the next few weeks, we'll hopefully have a nice containerised platform to build Debian packages from. It will only be for Debian, but once you have the source code building properly for Debian, you can probably upload to a PPA for Ubuntu. Hopefully, it'll just work :tm:! :smile: 

Sorry I haven't been into the chat, but I'm pretty flat out with work. Also our timezones are pretty out of whack, so not sure how that'd work?
 
I can't guarantee that I'll have a ton of time, but at the very least, I'll be able to assist with this.

Also thinking of testing, @SunyataZero did you say you run Ubuntu? Or did I imagine that?
What about you, @andy5995? I run Debian so testing for that is easy. My work laptop is Stretch and my desktop is Sid.

**Comment by SunyataZero** [comment]
I'm happy to read that you know some packaging because it's such a big hole in my skills, i love being able to work together (and maybe i can learn a thing or two in the process as well :) )

About chatting: Gitter is nice in that it saves messages, (it's more like slack than irc). Also gitter can send email notifications for missed messages which is practical as well

Testing: Yes i'm running on Lubuntu 16.04 (did you mean testing in general or of the packaging specifically?)

Kind Regards, Tord

**Comment by andy5995** [comment]
>Sorry I haven't been into the chat, but I'm pretty flat out with work. Also our timezones are pretty out of whack, so not sure how that'd work?

No need to worry about that, @JedMeister . As for the TZ, we just post, or answer, when we can. Sometimes hours might go by, and sometimes days. :)  With your default Gitter settings, you will receive notifications when someone has replied. If you close the chat and turn off the computer, the history of the chat will be there when you log back in.

I use Debian 9 (stretch). I could help you test packages if you need me.

**Comment by andy5995** [comment]
@SunyataZero you may want to start by adding a changelog that is formatted to Debian specifications. I think once all the required files are made, that would make it much easier for people who want to try building a package that meets specifications.

I haven't experimented yet with the GitHub "Projects" feature, but maybe this would be a good "Project" to start.

**Comment by SunyataZero** [comment]
Thank you for the suggestions, (i don't think i've used projects yet either, but maybe it's similar to waffle.io). Is it important to start right now with the changelog or can it wait? there's so many things right now... Kind Regards, Tord

**Comment by andy5995** [comment]
It's all up to you. :)

**Comment by SunyataZero** [comment]
Andy wrote: Because Ubuntu is based on Debian, I wonder if it would first be better to build a Debian package, and then adapt the Ubuntu package from that.

Also, are you wanting a package that meets Debian specifications, or just a package in Debian format that can be installed or removed with the Debian package manager.

To make a package that complies with the Debian policies, a few files will need to be added.

https://wiki.debian.org/Packaging/Intro?action=show&redirect=IntroDebianPackaging

Here is one example, mentioned in the link above

debian/changelog

First file is debian/changelog. This is the log of changes to the Debian package.

It does not need to list everything that has changed in upstream code, though it can be helpful to users to summarize those changes, too. Since we are now making the first version, there is nothing to log. However, we still need to make a changelog entry, because the packaging tools read certain information from the changelog. Most importantly, they read the version of the package.

debian/changelog has a very particular format. The easiest way to create it is to use the dch tool.

**Comment by SunyataZero** [comment]
@JedMeister wrote: FWIW if you can successfully build a Debian package which works, then it can (at least in theory) be rebuilt against any Debian based release and should also work there. As you're probably aware, a Debian package is built within a Debian chroot. You just use a different release chroot to build a different release package.

As @andy5995 notes, if you don't care about it getting into the official Debian repos, then you don't need to follow the Debian packaging policy (although it may still be a good idea).

If you go that way (i.e. don't do it "properly") and bundle it with it's dependencies (except python itself probably), you may be able to provide a single deb file that will install in most (if not all) Debian based distros/releases everywhere!? You'll never get it into Debian (or Ubuntu) repos like that though...

So it's worth considering whether your primary aim is to just want to make it easier to install in the short term? Or whether you'd like to get it into the official Debian repos (so it will be super easy to install at some point in the future).

If you'd like to get it into the official Debian repos (and Ubuntu too) at some point, then doing it properly right from the start is the best plan IMO. You may still be able to build a generic enough deb that it will install everywhere in the meantime, although YMMV.

**Comment by andy5995** [comment]
According to this, one must be a Debian maintainer to get his package into the Debian repo

https://www.debian.org/devel/join/

> Joining. After you have contributed for some time and are sure about your involvement in the Debian project, you can join Debian in a more official role. There are two different roles in which you might join Debian:

    Debian Maintainer (DM): The first step in which you can upload your own packages to the Debian archive yourself.
    Debian Developer (DD): The traditional full membership role in Debian. A DD can participate in Debian elections. Packaging DDs can upload any package to the archive. Before applying as a packaging DD you should have a track record of maintaining packages for at least six months. For example uploading packages as a DM, working inside a team or maintaining packages uploaded by sponsors. Non-packaging DDs have no permissions in the archive. Before applying as non-packaging DD, you should have a visible and significant track record of work inside the project.
