### ISSUE TITLE
Increasing code coverage

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#70]
Please note:
* This issue can be taken multiple times and by multiple people

**Comment by deferred** [comment]
Link doesn't work. Working link: https://codecov.io/gh/mindfulness-at-the-computer/mindfulness-at-the-computer

**Comment by SunyataZero** [comment]
@deferred Thank you for noting this, we have actually removed this code coverage tool now, after having moved to another domain name. Still code coverage can be increased by writing auto tests of course
