### ISSUE TITLE
Adding type hints to function headers

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#71]
Example:

```
def function(argument)
```
can be changed to
```
def function(argument: str)
```
if the expected in argument is a string

Type hints can also be used for the return value, for example:
```
def function() -> int
```
or if the function doesn't return anything:
```
def function() -> None
```

Please note that this issue can be taken multiple times and by multiple people

***

If you like the project you can help out by "starring" the project <3 This will help make it easier for others to find the project

**Comment by dgauraang** [comment]
Hi, I would like to work on this issue. Thank you!

**Comment by SunyataZero** [comment]
@dgauraang Welcome! Please go ahead! If there's anything you need help with please don't hesitate to ask if our [gitter chat](https://gitter.im/mindfulness-at-the-computer/Lobby) Kind Regards, Tord

**Comment by SunyataZero** [comment]
@nishusharma1608 Hi and welcome! Yes please feel free to work on this, you only need to change a one header with each commit+PR ("pull request") so the risk for collision with @dgauraang is small (but just in case you could say which file and function you will change if you want). Kind Regards, Tord

**Comment by wjiang0** [comment]
Hi @SunyataZero I would also like to help out with this issue. Do we have to limit one header change with each commit+PR? Or can we add hints to multiple function headers (each an individual commit) and make a single PR that way? If so, I'd like to work on the mc/mc_global.py file.

**Comment by SunyataZero** [comment]
Hi and welcome, yes please feel free to work on the whole file if you like. If you need help you can use the gitter.im chat. Kind Regards, Tord on mobile

**Comment by andrefouger** [comment]
Hi, I would like to work on this issue. Thank you!

**Comment by SunyataZero** [comment]
@andrefouger Hi and thank you for wanting to help with the application! Kind Regards, Tord

**Comment by MaskyS** [comment]
Close fixed issues please :)

**Comment by SunyataZero** [comment]
@MaskyS Hi and welcome, there are still functions without type hints so i'm leaving this open for now. Kind Regards, Tord

**Comment by Buzzmonolith** [comment]
@SunyataZero Hello, how can I contribute to your project?

**Comment by SunyataZero** [comment]
@Buzzmonolith Hi and welcome!

A couple of important links:
* You can read about the application from a user-perspective on the application website: https://sunyatazero.github.io/mindfulness-at-the-computer/
* Gitter chat: https://gitter.im/mindfulness-at-the-computer/Lobby
* https://github.com/SunyataZero/mindfulness-at-the-computer/blob/master/CONTRIBUTING.md

For the type hints issue: If you find a function in the source please add so called type hints, for example if a function `def function(argument)` takes a `str` as an in parameter you can write something like this: `def function(argument: str)`. It's also possible to add the return value at the end of the function header after `->`

Hope this helps you! Kind Regards, Tord

**Comment by mandarvaze** [comment]
I think [instagram's monkeytype tool](https://github.com/Instagram/MonkeyType) might be useful tool to automate a whole lot of this.

See https://engineering.instagram.com/let-your-code-type-hint-itself-introducing-open-source-monkeytype-a855c7284881

**Comment by SunyataZero** [comment]
@mandarvaze Thank you for the suggestion, i hadn't seen this before, interesting :+1: 

I'll keep the issue though as a good one for first-time contributors, it's useful for getting into the code, making a pull request and maybe will add more quality to the code in cases where the automated system has a hard time knowing our intentions for how the in-parameter will be used in the future

**Comment by Prash9** [comment]
Hi , can I work on this issue? .

**Comment by nishusharma1608** [comment]
ya sure

**Comment by MagdaZawora** [comment]
Hi @SunyataZero, do you still need help from a very 'first-timer"?:)

**Comment by SunyataZero** [comment]
@MagdaZawora Hi and welcome, this project is first-timer-friendly, we are happy to have your help! [This document](https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/blob/master/CONTRIBUTING.md) has a lot of good info on how to get started, and you can always ask in the [gitter lobby chat room](https://gitter.im/mindfulness-at-the-computer/Lobby) if you run into any problems. Kind Regards, Tord

**Comment by Soujen** [comment]
Hey, mind if I work on this issue? Thanks(:

**Comment by SunyataZero** [comment]
@Soujen Hi and welcome! Please feel free to work on this issue, also if you need any help you can join us in the [gitter chat](https://gitter.im/mindfulness-at-the-computer/Lobby) Kind Regards, Tord

**Comment by tankucukoglu** [comment]
#148

**Comment by tankucukoglu** [comment]
#148

**Comment by dhairyakhale** [comment]
Can I work on this issue? Thanks!

**Comment by SunyataZero** [comment]
@dgauraang You are very welcome to help out, thanks! I've invited you to [our gitter chat](https://gitter.im/mindfulness-at-the-computer/Lobby), please feel free to ask questions there about the application or contribution process. Kind Regards, Tord

**Comment by sanchaymittal** [comment]
Mind if i work on this issue?

**Comment by SunyataZero** [comment]
@sanchaymittal Please go ahead! And welcome :) Kind Regards, Tord

**Comment by goswami-rahul** [comment]
I am too taking this issue :)

**Comment by brentirwin** [comment]
Hi! I was browsing this project and noticed where I could help with this issue in db.py. A few instances of i_db_conn had type hints of sqlite3.Connection, and others did not (including some sample code meant to be copied and pasted later). I updated them all to match and will send a PR. Hope it helps!

**Comment by GonzaloUlla** [comment]
Hello! I've just added some type hints in model.py and I've made a new PR (#327)
