### ISSUE TITLE
Adding screenshots to the readme.md file

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#79]
Please use a height of about 140 px for the screenshots, and place them side by side in the readme.md file. The readme.md file uses markdown formatting, and images can be added like this: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images

**Comment by SunyataZero** [comment]
@VishalVatsal97 Hi and welcome! Please go ahead, i'll also invite you to the gitter chat https://gitter.im/mindfulness-at-the-computer/Lobby where you can ask any questions. Kind Regards, Tord

**Comment by yuzhoujr** [comment]
Can I please do this! First timer here

**Comment by yuzhoujr** [comment]
I don't mind helping, needs to know 2 things:
1. where do I find the screenshots?
2. what location you would like to me post on your md file.

**Comment by yuzhoujr** [comment]
I think I might have found the screenshots @ https://mindfulness-at-the-computer.github.io/screenshots/
Do you need all screenshots to be formatted under your rules? Can the image be cropped to have a relatively healthy looking?
Also where exactly are you needing them in the md files.

**Comment by SunyataZero** [comment]
@yuzhoujr Hi and welcome! You can use a screenshot tool to grab a few screenshots from the application, perhaps of the breathing dialog and of the settings window and one of the popups. I think the screenshots can perhaps be positioned right after the first paragraph of text in the readme file.

How do you mean cropped? I think that is okay though. If you want we can discuss more here:
https://gitter.im/mindfulness-at-the-computer/Lobby

Kind Regards, Tord
