### ISSUE TITLE
[MacOS] breathing and resting popups don't appear in full-screen windows

### ISSUE THREAD

**Issue by mbed67** [mindfulness-at-the-computer/mindfulness-at-the-computer#93]
I'm using a Mac and I noticed strange behavior when using full-screen windows.
On my Mac I can choose to create multiple desktops. And I can also set the current window to full screen. When the main application is situated on desktop 1 and I'm working on desktop 1 or 2, then I see the breathing and resting popups correctly. When I'm working in a full-screen window, I don't see the popups. The popups appear however in the desktop of the main application in that case.

**Comment by SunyataZero** [comment]
Thank you for reporting this, i've written a question about this here: https://stackoverflow.com/questions/47711138/show-popup-window-when-in-fullscreen-mode-on-macos

**Comment by SunyataZero** [comment]
Still a problem now
