### ISSUE TITLE
Improving new developer documentation

### ISSUE THREAD

**Issue by rogermeadows** [mindfulness-at-the-computer/mindfulness-at-the-computer#96]
As a new developer I am using the existing online documentation. When I encounter a question or problem that is not addressed in the current documentation, I will add to the existing documentation to address the new question or issue.

For example, it was not clear to me how to start Travis CI on my fork and how to find the results form Travis CI execution on the main repository. It was also not clear to me if issues were required for pull request. Once we decide on these issues, I will add documentation to reduce the learning curve for the next new developer. @SunyataZero

**Comment by SunyataZero** [comment]
Thank you for bringing this up, a developer friend of mine said to me "good documentation is what makes free and open source software projects succeed"

Another thing i was thinking about: Markdown is used in the docs/ directory, on the wiki and when chatting on gitter, maybe we can include a link to a quick guide to markdown somewhere? (Here is one guide: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

**Comment by rogermeadows** [comment]
That is a great idea. I will find a place for that link. I need the link
myself. I am having trouble formatting my replies to gitter messages. I
can't seem to get the block quote to work correctly. I will figure it out.
Thanks,
Roger

**Comment by SunyataZero** [comment]
@rogermeadows I've had my problems with the block quote myself, there are two things i have to keep in mind when using them: They end with an empty line and also i have to use `> ` for each new line inside of the quote itself. (Unfortunately many text editors doesn't make clear when there is a new line and when there's a word/line wrap)

**Comment by SunyataZero** [comment]
@rogermeadows Okay i now see that in gitter it's possible to use mark the text you want to want to quote and press `q`

I found this from the gitter shortcut menu which i found is available when pressing `ctrl`+`shift`+`alt`+`k`. (Also there is a markdown help menu in gitter you can reach by using `ctrl`+`shift`+`alt`+`m`)

**Comment by rogermeadows** [comment]
Thanks

**Comment by SunyataZero** [comment]
Once the application architecture has been established we could perhaps give a visual overview of the structure of the application
