### ISSUE TITLE
Creating a github organization for the project

### ISSUE THREAD

**Issue by SunyataZero** [mindfulness-at-the-computer/mindfulness-at-the-computer#98]
[Github Help - About repository transfers](https://help.github.com/articles/about-repository-transfers/)

Here's my todo list for transferring to the org:
* [x] https://github.com/SunyataZero/mindfulness-at-the-computer/settings
* [x] update links: up-for-grabs
* [x] code4socialgood
* [x] all other links on outreach
* [x] email newsletter tinyletter
* [x] documentation in the docs/ directory

**Comment by JedMeister** [comment]
:+1: 

IMO this is a really good idea! Then you'll be able to get trusted contributors more involved.

The default permissions levels are documented [here](https://help.github.com/articles/repository-permission-levels-for-an-organization/). Although IIRC there is fairly fine grained control beyond the defaults once you've got the org set up.

I'd recommend that once you do that, you [protect](https://help.github.com/articles/about-protected-branches/) at least your master branch, perhaps others too? You can also require that pull requests are [reviewed](https://help.github.com/articles/about-pull-request-reviews/) before they can be merged.
